services:
  postgres:
    image: postgres:15-alpine
    container_name: homework_04_postgres
    environment:
      POSTGRES_DB: homework_db
      POSTGRES_USER: homework_user
      POSTGRES_PASSWORD: homework_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homework_user -d homework_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
